apiVersion: eksctl.io/v1alpha5

metadata:
  name: DEFAULT-CLUSTER-NAME
  region: us-west-2
  version: "1.28"

privateCluster:
  enabled: false
  skipEndpointCreation: false

vpc:
  autoAllocateIPv6: false
  cidr: 192.168.0.0/24
  clusterEndpoints:
    privateAccess: false
    publicAccess: true
  manageSharedNodeSecurityGroupRules: true
  nat:
    gateway: Single

availabilityZones:
  - us-west-2b
  - us-west-2a

cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authenticator", "controllerManager", "scheduler"]
    logRetentionInDays: 60

iam:
  vpcResourceControllerPolicy: true
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true
    - metadata:
        name: external-dns
        namespace: kube-system
      wellKnownPolicies:
        externalDNS: true
    - metadata:
        name: cert-manager
        namespace: cert-manager
      wellKnownPolicies:
        certManager: true

kind: ClusterConfig

kubernetesNetworkConfig:
  ipFamily: IPv4

managedNodeGroups:
  - amiFamily: Ubuntu2004
    desiredCapacity: 2
    disableIMDSv1: true
    disablePodIMDS: false
    availabilityZones: ["us-west-2a"]
    iam:
      withAddonPolicies:
        albIngress: false
        appMesh: false
        appMeshPreview: false
        autoScaler: false
        awsLoadBalancerController: false
        certManager: false
        cloudWatch: false
        ebs: false
        efs: false
        externalDNS: false
        fsx: false
        imageBuilder: false
        xRay: false
    instanceSelector: {}
    instanceType: c5.xlarge
    labels:
      alpha.eksctl.io/cluster-name: DEFAULT-CLUSTER-NAME
      alpha.eksctl.io/nodegroup-name: DEFAULT-CLUSTER-NAME-ng1
    maxSize: 2
    minSize: 0
    name: DEFAULT-CLUSTER-NAME-ng1
    privateNetworking: false
    releaseVersion: ""
    securityGroups:
      withLocal: null
      withShared: null
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/id_rsa.pub
    tags:
      alpha.eksctl.io/nodegroup-name: DEFAULT-CLUSTER-NAME-ng1
      alpha.eksctl.io/nodegroup-type: managed
    volumeIOPS: 3000
    volumeSize: 80
    volumeThroughput: 125
    volumeType: gp3
  - amiFamily: Ubuntu2004
    desiredCapacity: 2
    disableIMDSv1: true
    disablePodIMDS: false
    availabilityZones: ["us-west-2b"]
    iam:
      withAddonPolicies:
        albIngress: false
        appMesh: false
        appMeshPreview: false
        autoScaler: false
        awsLoadBalancerController: false
        certManager: false
        cloudWatch: false
        ebs: false
        efs: false
        externalDNS: false
        fsx: false
        imageBuilder: false
        xRay: false
    instanceSelector: {}
    instanceType: c5.xlarge
    labels:
      alpha.eksctl.io/cluster-name: DEFAULT-CLUSTER-NAME
      alpha.eksctl.io/nodegroup-name: DEFAULT-CLUSTER-NAME-ng2
    maxSize: 2
    minSize: 0
    name: DEFAULT-CLUSTER-NAME-ng2
    privateNetworking: false
    releaseVersion: ""
    securityGroups:
      withLocal: null
      withShared: null
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/id_rsa.pub
    tags:
      alpha.eksctl.io/nodegroup-name: DEFAULT-CLUSTER-NAME-ng2
      alpha.eksctl.io/nodegroup-type: managed
    volumeIOPS: 3000
    volumeSize: 80
    volumeThroughput: 125
    volumeType: gp3